name: Deploy to Homelab

on:
  workflow_run:
    workflows:
      - Validate Project
    types: [completed]
  workflow_dispatch:

jobs:
  check-validations:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: Check Validations
    runs-on: ubuntu-latest
    steps:
      - run: echo "Validations Passed"

  trigger-deploy-to-homelab:
    if: github.ref == 'refs/heads/main'
    name: Trigger Deploy to Homelab
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://hooks.ichrisbirch.com/hooks/ichrisbirch \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$(echo -n '{}' | openssl dgst -sha256 -hmac '${{ secrets.WEBHOOK_SECRET }}' | cut -d' ' -f2)" \
            -d '{}'
